#!/usr/bin/env php
<?php

// Setup as per http://www.sitepoint.com/command-line-php-using-symfony-console/

// set to run indefinitely if needed
set_time_limit(0);

/* Optional. It’s better to do it in the php.ini file */
date_default_timezone_set('Europe/Helsinki'); 

// include the composer autoloader
require_once __DIR__ . '/../vendor/autoload.php'; 

// import the Symfony Console Application 
use Symfony\Component\Console\Application; 
use Data\Commands\Process;
use Data\Commands\Createindex;

$app = new Application();
$app->add(new Process());
$app->add(new Createindex());
$app->run();
?>